### ISSUE TITLE
crash in SendRoutingMessage

### ISSUE THREAD

**Issue by despair86** [loki-project/loki-network#192]
uninitialised memory access in `llarp::path::Path::SendRoutingMessage(const llarp::routing::IMessage* msg, llarp::router* r)`

`msg` is valid but points to garbage

this only happens when the endpoint is a service node

as far as i can tell, this does not affect hidden svc nodes. i am also unable to reproduce this bug on my old VMs. Because they are allowed to execute on any one (1) physical CPU by the hypervisor.

**update: multiprocessor systems only**
```
#0  0x0041cad0 in llarp::path::Path::SendRoutingMessage (this=0xac2bfb8, msg=0xac40050, r=0xac141a8) at ../llarp/path.cpp:589
#1  0x0044b550 in llarp::exit::BaseSession::Flush (this=0xac28170) at ../llarp/exit/session.cpp:195
#2  0x0043342c in llarp::service::Endpoint::FlushSNodeTraffic (this=0xcb90020) at ../llarp/service/endpoint.cpp:132
#3  0x00453fba in llarp::handlers::TunEndpoint::tunifBeforeWrite (tun=0xcb914c0) at ../llarp/handlers/tun.cpp:647
#4  0x004e91f9 in win32_tun_io::flush_write (this=0xac22628) at ../llarp/ev_win32.hpp:144
#5  0x004677bb in tun_ev_loop@4 (unused=0x0) at ../llarp/ev_win32.hpp:204
#6  0x749e60c9 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#7  0x771f6004 in ntdll!RtlGetAppContainerNamedObjectPath () from C:\WINDOWS\SYSTEM32\ntdll.dll
#8  0x771f5fd4 in ntdll!RtlGetAppContainerNamedObjectPath () from C:\WINDOWS\SYSTEM32\ntdll.dll
#9  0x00000000 in ?? ()
```
```
>>> p msg
$1 = (const llarp::routing::IMessage *) 0xc4cbec0
>>> p *msg
$2 = {
  <llarp::IBEncodeMessage> = {
    _vptr.IBEncodeMessage = 0xbaadf00d, <-- special pattern used by NT kernel allocator
    version = 13451671603782742029
  },
  members of llarp::routing::IMessage:
  from = {
    static SIZE = 16,
    val = {
      __data = "\r▒\r▒\r▒\r▒",
      __align = {<No data fields>}
    }
  },
  S = 7
}
```

**Comment by majestrate** [comment]
this is probably happening because the parsing code assumes it is always run in a singled threaded way.

**Comment by neuroscr** [comment]
master or staging? if staging, pls use the staging tag

**Comment by despair86** [comment]
master. I haven't even got around to staging yet

**Comment by neuroscr** [comment]
I can confirm that commit 54249f30d48510ae13864363be26db06004a7b5e on master is stable, so must be a commit after this that broke it.

**Comment by majestrate** [comment]
that codepath is not thread safe, make sure you call that in the main event thread
