### ISSUE TITLE
bad allocation when node tries to connect out

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#231]
loki-staging2-5 died after a bit with a bad_alloc
loki-staging1 the seed node stays online

So I'm thinking it has to do with the external connecting

**Comment by michael-loki** [comment]
did you get a stacktrace?

**Comment by neuroscr** [comment]
not yet, I was trying to replicate on MacOS without success, so I could use my good debugger. I'll try with gdb now.

**Comment by neuroscr** [comment]
Finally got it (looks like it takes about 4 hours if I have all 5 running but happens much faster if I just have the seed and a single)

```
ERR] (247) Thu Jan 17 08:32:29 2019 UTC llarp/router.cpp:87	did not attempt connection to 0db5bdf8862ce02c356e67f7c3dbbc03ebf0e283b096a414ac6dec996d51f0ac and it has 1 advertised addresses
[ERR] (247) Thu Jan 17 08:32:29 2019 UTC llarp/link/utp.cpp:337	UTP_ETIMEDOUT via 206.81.100.174:2091
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Thread 1 "lokinet-staging" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6ec1801 in __GI_abort () at abort.c:79
#2  0x00007ffff7ad38fb in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7ad9d3a in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7ad9d95 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7ada03d in __cxa_rethrow () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00005555555a6b0a in std::__uninitialized_copy<false>::__uninit_copy<__gnu_cxx::__normal_iterator<llarp::AddressInfo const*, std::vector<llarp::AddressInfo, std::allocator<llarp::AddressInfo> > >, llarp::AddressInfo*> (__first=
  {<llarp::IBEncodeMessage> = {_vptr.IBEncodeMessage = 0x555555b20a60, version = 3761112758277526085}, rank = 10551, dialect = <error: Cannot access memory at address 0x3830203731206e61>, pubkey = {<llarp::AlignedBuffer<32>> = {static SIZE = 32, val = {__data = "nk/utp.cpp:337\tUTP_ETIMEDOUT via", __align = {<No data fields>}}}, <No data fields>}, ip = {__in6_u = {__u6_addr8 = " 206.81.100.174:", __u6_addr16 = {12832, 13872, 14382, 11825, 12337, 11824, 14129, 14900}, __u6_addr32 = {909128224, 774977582, 774910001, 976500529}}}, port = 12338}, __last=
  {<llarp::IBEncodeMessage> = {_vptr.IBEncodeMessage = 0x6d30, version = 145}, rank = 0, dialect = "", pubkey = {<llarp::AlignedBuffer<32>> = {static SIZE = 32, val = {__data = '\000' <repeats 31 times>, __align = {<No data fields>}}}, <No data fields>}, ip = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, port = 0}, __result=0x555555af6f00)
    at /usr/include/c++/7/bits/stl_uninitialized.h:89
#7  0x00005555555a11e6 in std::uninitialized_copy<__gnu_cxx::__normal_iterator<llarp::AddressInfo const*, std::vector<llarp::AddressInfo, std::allocator<llarp::AddressInfo> > >, llarp::AddressInfo*> (__first=
  {<llarp::IBEncodeMessage> = {_vptr.IBEncodeMessage = 0x555555b20a60, version = 3761112758277526085}, rank = 10551, dialect = <error: Cannot access memory at address 0x3830203731206e61>, pubkey = {<llarp::AlignedBuffer<32>> = {static SIZE = 32, val = {__data = "nk/utp.cpp:337\tUTP_ETIMEDOUT via", __align = {<No data fields>}}}, <No data fields>}, ip = {__in6_u = {__u6_addr8 = " 206.81.100.174:", __u6_addr16 = {12832, 13872, 14382, 11825, 12337, 11824, 14129, 14900}, __u6_addr32 = {909128224, 774977582, 774910001, 976500529}}}, port = 12338}, __last=
  {<llarp::IBEncodeMessage> = {_vptr.IBEncodeMessage = 0x6d30, version = 145}, rank = 0, dialect = "", pubkey = {<llarp::AlignedBuffer<32>> = {static SIZE = 32, val = {__data = '\000' <repeats 31 times>, __align = {<No data fields>}}}, <No data fields>}, ip = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, port = 0}, __result=0x555555af6f00)
    at /usr/include/c++/7/bits/stl_uninitialized.h:134
#8  0x000055555559b1ff in std::__uninitialized_copy_a<__gnu_cxx::__normal_iterator<llarp::AddressInfo const*, std::vector<llarp::AddressInfo, std::allocator<llarp::AddressInfo> > >, llarp::AddressInfo*, llarp::AddressInfo> (__first=
---Type <return> to continue, or q <return> to quit---
  {<llarp::IBEncodeMessage> = {_vptr.IBEncodeMessage = 0x555555b20a60, version = 3761112758277526085}, rank = 10551, dialect = <error: Cannot access memory at address 0x3830203731206e61>, pubkey = {<llarp::AlignedBuffer<32>> = {static SIZE = 32, val = {__data = "nk/utp.cpp:337\tUTP_ETIMEDOUT via", __align = {<No data fields>}}}, <No data fields>}, ip = {__in6_u = {__u6_addr8 = " 206.81.100.174:", __u6_addr16 = {12832, 13872, 14382, 11825, 12337, 11824, 14129, 14900}, __u6_addr32 = {909128224, 774977582, 774910001, 976500529}}}, port = 12338}, __last=
  {<llarp::IBEncodeMessage> = {_vptr.IBEncodeMessage = 0x6d30, version = 145}, rank = 0, dialect = "", pubkey = {<llarp::AlignedBuffer<32>> = {static SIZE = 32, val = {__data = '\000' <repeats 31 times>, __align = {<No data fields>}}}, <No data fields>}, ip = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, port = 0}, __result=0x555555af6f00)
    at /usr/include/c++/7/bits/stl_uninitialized.h:289
#9  0x0000555555591d17 in std::vector<llarp::AddressInfo, std::allocator<llarp::AddressInfo> >::vector (this=0x7fffffffdf90, __x=std::vector of length 1, capacity 1 = {...})
    at /usr/include/c++/7/bits/stl_vector.h:331
#10 0x000055555558d30f in llarp::RouterContact::RouterContact (this=0x7fffffffdf80, other=...) at /root/loki-network-staging/llarp/router_contact.hpp:76
#11 0x0000555555612bfe in TryConnectJob::Attempt (this=0x555555af2ba0) at /root/loki-network-staging/llarp/router.cpp:84
#12 0x0000555555607830 in on_try_connecting (u=0x555555af2ba0) at /root/loki-network-staging/llarp/router.cpp:104
#13 0x00005555557476b9 in std::__invoke_impl<void, void (*&)(void*), void*&> (__f=@0x555555b42e90: 0x555555607810 <on_try_connecting(void*)>, __args#0=@0x555555b42e98: 0x555555af2ba0)
    at /usr/include/c++/7/bits/invoke.h:60
#14 0x0000555555747310 in std::__invoke<void (*&)(void*), void*&> (__fn=@0x555555b42e90: 0x555555607810 <on_try_connecting(void*)>, __args#0=@0x555555b42e98: 0x555555af2ba0)
    at /usr/include/c++/7/bits/invoke.h:95
#15 0x0000555555746e23 in std::_Bind<void (*(void*))(void*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x555555b42e90, __args=...) at /usr/include/c++/7/functional:467
#16 0x0000555555746711 in std::_Bind<void (*(void*))(void*)>::operator()<, void>() (this=0x555555b42e90) at /usr/include/c++/7/functional:551
#17 0x00005555557460e5 in std::_Function_handler<void (), std::_Bind<void (*(void*))(void*)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#18 0x00005555557032ac in std::function<void ()>::operator()() const (this=0x7fffffffe230) at /usr/include/c++/7/bits/std_function.h:706
#19 0x0000555555745569 in llarp_threadpool_tick (pool=0x555555adfcb0) at /root/loki-network-staging/llarp/util/threadpool.cpp:101
#20 0x00005555557446ed in llarp::Logic::tick_async (this=0x555555ae0670, now=1547713949424) at /root/loki-network-staging/llarp/util/logic.cpp:20
#21 0x0000555555751ef7 in llarp_ev_loop_run_single_process (ev=0x555555ade8a0, tp=0x555555adf8e0, logic=0x555555ae0670) at /root/loki-network-staging/llarp/ev/ev.cpp:77
#22 0x0000555555578df8 in llarp::Context::Run (this=0x555555addcd0) at /root/loki-network-staging/llarp/context.cpp:182
---Type <return> to continue, or q <return> to quit---
#23 0x0000555555579506 in llarp_main_run (ptr=0x555555addcb0) at /root/loki-network-staging/llarp/context.cpp:352
#24 0x0000555555568caf in main (argc=2, argv=0x7fffffffe568) at /root/loki-network-staging/daemon/main.cpp:186
```

**Comment by neuroscr** [comment]
my staging testnet has been running over 24 hours.
