### ISSUE TITLE
mTestBencode/ReadStr.readStr/6 failure on macOS

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#263]
```
[0;32m[----------] [m12 tests from TestBencode/ReadStr
[0;32m[ RUN      ] [mTestBencode/ReadStr.readStr/0
[0;32m[       OK ] [mTestBencode/ReadStr.readStr/0 (0 ms)
[0;32m[ RUN      ] [mTestBencode/ReadStr.readStr/1
[0;32m[       OK ] [mTestBencode/ReadStr.readStr/1 (0 ms)
[0;32m[ RUN      ] [mTestBencode/ReadStr.readStr/2
[0;32m[       OK ] [mTestBencode/ReadStr.readStr/2 (0 ms)
[0;32m[ RUN      ] [mTestBencode/ReadStr.readStr/3
[0;32m[       OK ] [mTestBencode/ReadStr.readStr/3 (0 ms)
[0;32m[ RUN      ] [mTestBencode/ReadStr.readStr/4
[0;32m[       OK ] [mTestBencode/ReadStr.readStr/4 (0 ms)
[0;32m[ RUN      ] [mTestBencode/ReadStr.readStr/5
[0;32m[       OK ] [mTestBencode/ReadStr.readStr/5 (0 ms)
[0;32m[ RUN      ] [mTestBencode/ReadStr.readStr/6
=================================================================
==42958==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000f0d32 at pc 0x0001014cf997 bp 0x7fff5fbfe2f0 sp 0x7fff5fbfe2e8
READ of size 1 at 0x6020000f0d32 thread T0
    #0 0x1014cf996 in llarp_buffer_read_until(llarp_buffer_t*, char, unsigned char*, unsigned long) buffer.cpp:53
    #1 0x1014c939e in bencode_read_string(llarp_buffer_t*, llarp_buffer_t*) bencode.cpp:38
    #2 0x10060c0cb in ReadStr_readStr_Test::TestBody() test_llarp_util_bencode.cpp:96
    #3 0x100966859 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2424
    #4 0x100966560 in testing::Test::Run() gtest.cc:2499
    #5 0x10096a6b7 in testing::TestInfo::Run() gtest.cc:2675
    #6 0x10096c526 in testing::TestSuite::Run() gtest.cc:2803
    #7 0x10099b216 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5241
    #8 0x100999e59 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2424
    #9 0x100999bb2 in testing::UnitTest::Run() gtest.cc:4843
    #10 0x1003a5570 in RUN_ALL_TESTS() gtest.h:2499
    #11 0x1003a54e5 in main main.cpp:28
    #12 0x7fff8b951234 in start (libdyld.dylib:x86_64+0x5234)

0x6020000f0d32 is located 0 bytes to the right of 2-byte region [0x6020000f0d30,0x6020000f0d32)
allocated by thread T0 here:
    #0 0x10251e0ab in wrap__Znwm (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x640ab)
    #1 0x100308f70 in std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::allocate(unsigned long) new:226
    #2 0x10063082d in std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::vector(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&) vector:1200
    #3 0x10063034c in std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >::vector(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&) vector:1193
    #4 0x10063d65e in TestReadData<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::TestReadData(TestReadData<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) test_llarp_util_bencode.cpp:14
    #5 0x10060cf7c in TestReadData<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::TestReadData(TestReadData<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) test_llarp_util_bencode.cpp:14
    #6 0x10060c062 in ReadStr_readStr_Test::TestBody() test_llarp_util_bencode.cpp:91
    #7 0x100966859 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2424
    #8 0x100966560 in testing::Test::Run() gtest.cc:2499
    #9 0x10096a6b7 in testing::TestInfo::Run() gtest.cc:2675
    #10 0x10096c526 in testing::TestSuite::Run() gtest.cc:2803
    #11 0x10099b216 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5241
    #12 0x100999e59 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2424
    #13 0x100999bb2 in testing::UnitTest::Run() gtest.cc:4843
    #14 0x1003a5570 in RUN_ALL_TESTS() gtest.h:2499
    #15 0x1003a54e5 in main main.cpp:28
    #16 0x7fff8b951234 in start (libdyld.dylib:x86_64+0x5234)

SUMMARY: AddressSanitizer: heap-buffer-overflow buffer.cpp:53 in llarp_buffer_read_until(llarp_buffer_t*, char, unsigned char*, unsigned long)
Shadow bytes around the buggy address:
  0x1c040001e150: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c040001e160: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c040001e170: fa fa fd fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c040001e180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x1c040001e190: fa fa fa fa fa fa fd fa fa fa fa fa fa fa fa fa
=>0x1c040001e1a0: fa fa fa fa fa fa[02]fa fa fa fd fa fa fa fa fa
  0x1c040001e1b0: fa fa fa fa fa fa fd fa fa fa fa fa fa fa fa fa
  0x1c040001e1c0: fa fa fa fa fa fa fa fa fa fa fd fa fa fa fd fa
  0x1c040001e1d0: fa fa fa fa fa fa fd fa fa fa fa fa fa fa fd fd
  0x1c040001e1e0: fa fa fa fa fa fa fa fa fa fa fd fa fa fa fd fa
  0x1c040001e1f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
```

**Comment by neuroscr** [comment]
minor issue, probably didn't have much real world affect but now fixed
