### ISSUE TITLE
Lokinet crash with debugging symbols

### ISSUE THREAD

**Issue by BeaudanBrown** [loki-project/loki-network#379]
One of my relays crashed, with final output
`corrupted size vs. prev_size`
Here is the coredump file with debugging symbols (thanks jaff)
https://my.mixtape.moe/jjvjkt.coredump

**Comment by BeaudanBrown** [comment]
Backtrace
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f597c2f6801 in __GI_abort () at abort.c:79
#2  0x00007f597c33f897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f597c46cb9a "%s\n")
    at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f597c34690a in malloc_printerr (str=str@entry=0x7f597c46ac9d "corrupted size vs. prev_size")
    at malloc.c:5350
#4  0x00007f597c34b20e in _int_malloc (av=av@entry=0x7f597c6a1c40 <main_arena>, bytes=bytes@entry=128)
    at malloc.c:3926
#5  0x00007f597c3500b1 in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3436
#6  0x0000563dbdb1d90b in utp_create_socket (ctx=0x563dbfbf2130)
    at /home/jeff/git/loki-network/libutp/utp_internal.cpp:3016
#7  0x0000563dbdab3b6e in llarp::utp::LinkLayer::NewOutboundSession (this=0x563dbfbf1d30, rc=..., addr=...)
    at /home/jeff/git/loki-network/llarp/link/utp.cpp:850
#8  0x0000563dbdaa7ddb in llarp::ILinkLayer::TryEstablishTo (this=0x563dbfbf1d30, rc=...)
    at /home/jeff/git/loki-network/llarp/link/server.cpp:205
#9  0x0000563dbd94157c in TryConnectJob::Attempt (this=0x563dbfbf6930)
    at /home/jeff/git/loki-network/llarp/router/router.cpp:92
#10 0x0000563dbd932c44 in on_try_connecting (u=0x563dbfbf6930)
    at /home/jeff/git/loki-network/llarp/router/router.cpp:113
#11 0x0000563dbdb6a2c7 in std::__invoke_impl<void, void (*&)(void*), void*&> (
    __f=@0x563dbfc6a110: 0x563dbd932c24 <on_try_connecting(void*)>, __args#0=@0x563dbfc6a118: 0x563dbfbf6930)
    at /usr/include/c++/7/bits/invoke.h:60
#12 0x0000563dbdb69fbc in std::__invoke<void (*&)(void*), void*&> (
    __fn=@0x563dbfc6a110: 0x563dbd932c24 <on_try_connecting(void*)>, __args#0=@0x563dbfc6a118: 0x563dbfbf6930)
    at /usr/include/c++/7/bits/invoke.h:95
#13 0x0000563dbdb69bb5 in std::_Bind<void (*(void*))(void*)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x563dbfc6a110, __args=...) at /usr/include/c++/7/functional:467
#14 0x0000563dbdb695cf in std::_Bind<void (*(void*))(void*)>::operator()<, void>() (this=0x563dbfc6a110)
    at /usr/include/c++/7/functional:551
#15 0x0000563dbdb691b5 in std::_Function_handler<void (), std::_Bind<void (*(void*))(void*)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#16 0x0000563dbdaa992c in std::function<void ()>::operator()() const (this=0x7ffc463406d0)
    at /usr/include/c++/7/bits/std_function.h:706
#17 0x0000563dbdb68a0a in llarp_threadpool_tick (pool=0x563dbfbde6c0)
    at /home/jeff/git/loki-network/llarp/util/threadpool.cpp:82
#18 0x0000563dbdb60b39 in llarp::Logic::tick_async (this=0x563dbfbe1340, now=1551756408064)
    at /home/jeff/git/loki-network/llarp/util/logic.cpp:20
#19 0x0000563dbdb34232 in llarp_ev_loop_run_single_process (ev=0x563dbfbe2560, tp=0x563dbfbe1ac0,
    logic=0x563dbfbe1340) at /home/jeff/git/loki-network/llarp/ev/ev.cpp:100
#20 0x0000563dbd90ed2b in llarp::Context::Run (this=0x563dbfbde770)
    at /home/jeff/git/loki-network/llarp/context.cpp:198
#21 0x0000563dbd90f71e in llarp_main_run (ptr=0x563dbfbde750) at /home/jeff/git/loki-network/llarp/context.cpp:386
#22 0x0000563dbd8fc3ee in main (argc=2, argv=0x7ffc46340a38) at /home/jeff/git/loki-network/daemon/main.cpp:249
```

**Comment by majestrate** [comment]
On Mon, Mar 04, 2019 at 10:36:50PM -0800, Beaudan Campbell-Brown wrote:
> Backtrace
> ```
> #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
> #1  0x00007f597c2f6801 in __GI_abort () at abort.c:79
> #2  0x00007f597c33f897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f597c46cb9a "%s\n")
>     at ../sysdeps/posix/libc_fatal.c:181
> #3  0x00007f597c34690a in malloc_printerr (str=str@entry=0x7f597c46ac9d "corrupted size vs. prev_size")
>     at malloc.c:5350
> #4  0x00007f597c34b20e in _int_malloc (av=av@entry=0x7f597c6a1c40 <main_arena>, bytes=bytes@entry=128)
>     at malloc.c:3926
> #5  0x00007f597c3500b1 in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3436
> #6  0x0000563dbdb1d90b in utp_create_socket (ctx=0x563dbfbf2130)
>     at /home/jeff/git/loki-network/libutp/utp_internal.cpp:3016

ooooffff this died at a second call to calloc()

not sure what would cause this, don't want to say it's a glibc bug but you never know. I'll try a musl build.

**Comment by BeaudanBrown** [comment]
Closing as I haven't had a relay crash in a couple weeks
