### ISSUE TITLE
crash in metrics code on arm

### ISSUE THREAD

**Issue by majestrate** [loki-project/loki-network#753]
```
#0  0x003098d6 in std::uncaught_exception() ()
#1  0x00326ca2 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, int) ()
#2  0x0023c2cc in absl::lts_2018_12_18::operator<< (os=..., t=...) at /usr/local/src/loki-network/vendor/abseil-cpp/absl/time/time.h:1242
#3  0x0023b032 in llarp::metrics::StreamPublisher::publish (this=0x76601e8c, values=...) at /usr/local/src/loki-network/llarp/metrics/stream_publisher.cpp:169
#4  0x00278716 in llarp::metrics::PublisherHelper::publish<llarp::metrics::Category const**> (manager=..., categoriesBegin=@0x765fe978: 0x72c00498, categoriesEnd=@0x765fe97c: 0x72c004b8, clear=true)
    at /usr/local/src/loki-network/llarp/util/metrics_core.cpp:336
#5  0x002741fa in llarp::metrics::Manager::publish (this=0x76601b00, categories=..., clear=true) at /usr/local/src/loki-network/llarp/util/metrics_core.cpp:420
#6  0x00275f68 in llarp::metrics::Manager::publishAll (this=0x76601b00, clear=true) at /usr/local/src/loki-network/llarp/util/metrics_core.hpp:778
#7  0x00275ff0 in llarp::metrics::Manager::publishAllExcluding (this=0x76601b00, excludeCategories=..., clear=true) at /usr/local/src/loki-network/llarp/util/metrics_core.hpp:787
#8  0x0027428a in llarp::metrics::PublisherScheduler::publish (this=0x76601c40, data=...) at /usr/local/src/loki-network/llarp/util/metrics_core.cpp:490
#9  0x00289b64 in std::__invoke_impl<void, void (llarp::metrics::PublisherScheduler::* const&)(std::shared_ptr<llarp::metrics::PublisherSchedulerData> const&) const, llarp::metrics::PublisherScheduler*&, std::shared_ptr<llarp::metrics::PublisherSchedulerData>&> (__f=
    @0x76600900: (void (llarp::metrics::PublisherScheduler::*)(const llarp::metrics::PublisherScheduler * const, const std::shared_ptr<llarp::metrics::PublisherSchedulerData> &)) 0x27423d <llarp::metrics::PublisherScheduler::publish(std::shared_ptr<llarp::metrics::PublisherSchedulerData> const&) const>, __t=@0x76600910: 0x76601c40, __args#0=...) at /usr/arm-linux-gnueabihf/include/c++/6/functional:227
#10 0x002881d2 in std::__invoke<void (llarp::metrics::PublisherScheduler::* const&)(std::shared_ptr<llarp::metrics::PublisherSchedulerData> const&) const, llarp::metrics::PublisherScheduler*&, std::shared_ptr<llarp::metrics::PublisherSchedulerData>&> (__fn=
    @0x76600900: (void (llarp::metrics::PublisherScheduler::*)(const llarp::metrics::PublisherScheduler * const, const std::shared_ptr<llarp::metrics::PublisherSchedulerData> &)) 0x27423d <llarp::metrics::PublisherScheduler::publish(std::shared_ptr<llarp::metrics::PublisherSchedulerData> const&) const>, __args#0=@0x76600910: 0x76601c40, __args#1=...) at /usr/arm-linux-gnueabihf/include/c++/6/functional:251
#11 0x002860d4 in std::_Mem_fn_base<void (llarp::metrics::PublisherScheduler::*)(std::shared_ptr<llarp::metrics::PublisherSchedulerData> const&) const, true>::operator()<llarp::metrics::PublisherScheduler*&, std::shared_ptr<llarp::metrics::PublisherSchedulerData>&> (this=0x76600900, __args#0=@0x76600910: 0x76601c40, __args#1=...) at /usr/arm-linux-gnueabihf/include/c++/6/functional:604
#12 0x00284534 in std::_Bind<std::_Mem_fn<void (llarp::metrics::PublisherScheduler::*)(std::shared_ptr<llarp::metrics::PublisherSchedulerData> const&) const> (llarp::metrics::PublisherScheduler*, std::shared_ptr<llarp::metrics::PublisherSchedulerData>)>::__call<void, , 0u, 1u>(std::tuple<>&&, std::_Index_tuple<0u, 1u>) (this=0x76600900, __args=...) at /usr/arm-linux-gnueabihf/include/c++/6/functional:934
#13 0x002813d0 in std::_Bind<std::_Mem_fn<void (llarp::metrics::PublisherScheduler::*)(std::shared_ptr<llarp::metrics::PublisherSchedulerData> const&) const> (llarp::metrics::PublisherScheduler*, std::shared_ptr<llarp::metrics::PublisherSchedulerData>)>::operator()<, void>() (this=0x76600900) at /usr/arm-linux-gnueabihf/include/c++/6/functional:993
#14 0x0027cd84 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (llarp::metrics::PublisherScheduler::*)(std::shared_ptr<llarp::metrics::PublisherSchedulerData> const&) const> (llarp::metrics::PublisherScheduler*, std::shared_ptr<llarp::metrics::PublisherSchedulerData>)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/arm-linux-gnueabihf/include/c++/6/functional:1731
#15 0x000583ec in std::function<void ()>::operator()() const (this=0x76601d28) at /usr/arm-linux-gnueabihf/include/c++/6/functional:2127
#16 0x00055882 in llarp::thread::Scheduler::defaultDispatcher()::{lambda(std::function<void ()> const&)#1}::operator()(std::function<void ()> const&) const (__closure=0x76602464, callback=...)
    at /usr/local/src/loki-network/llarp/util/scheduler.hpp:113
#17 0x0005bc1a in std::_Function_handler<void (std::function<void ()> const&), llarp::thread::Scheduler::defaultDispatcher()::{lambda(std::function<void ()> const&)#1}>::_M_invoke(std::_Any_data const&, std::function<void ()> const&) (
    __functor=..., __args#0=...) at /usr/arm-linux-gnueabihf/include/c++/6/functional:1731
#18 0x0029129c in std::function<void (std::function<void ()> const&)>::operator()(std::function<void ()> const&) const (this=0x76602464, __args#0=...) at /usr/arm-linux-gnueabihf/include/c++/6/functional:2127
#19 0x0028fb8e in llarp::thread::Scheduler::dispatch (this=0x766023b8) at /usr/local/src/loki-network/llarp/util/scheduler.cpp:113
#20 0x0029a640 in std::__invoke_impl<void, void (llarp::thread::Scheduler::* const&)(), llarp::thread::Scheduler*> (
    __f=@0x76601aa0: (void (llarp::thread::Scheduler::*)(llarp::thread::Scheduler * const)) 0x28f6e3 <llarp::thread::Scheduler::dispatch()>, __t=@0x76601a9c: 0x766023b8) at /usr/arm-linux-gnueabihf/include/c++/6/functional:227
```

**Comment by michael-loki** [comment]
1. I hate ARMs memory model with a fiery passion
2. I will have to dig out my RPI

**Comment by majestrate** [comment]
we can disable metrics by default as a temp work around so that ARM builds don't die every 30 seconds with default configs. see #754
