### ISSUE TITLE
lokinet --background broke 

### ISSUE THREAD

**Issue by notlesh** [loki-project/loki-network#865]
**Describe the bug**

Running lokinet in `--background` mode broke recently, I suspect as a result of  #850 (Multithreaded cryptography). lokinet segfaults in `llarp::Logic::queue_func()` when it tries to dereference `link->m_Logic`, which is null. See a full `gdb backtrace` below.

**To Reproduce**

On a recent (e.g.  281fbff) build, run lokinet with `--background`.

**Screenshots Or Logs**

See my `gdb backtrace` in the following post.

**Device and Operating system (please complete the following information):**
 - OS: `Linux (Ubuntu 19.04) 64-bit`
-  Device: `Desktop (etc.)`
 - Lokinet Version number or Git commit hash:`281fbff`

**Comment by notlesh** [comment]
GDB backtrace:

```gdb
0x000055555592d368 in llarp::Logic::queue_func(std::function<void ()>&&) (this=0x0, f=...) at /home/stephen/dev/loki-network/llarp/util/thread/logic.cpp:74
74          if(!this->thread->impl->tryAddJob(f))
(gdb) bt
#0  0x000055555592d368 in llarp::Logic::queue_func(std::function<void ()>&&) (this=0x0, f=...) at /home/stephen/dev/loki-network/llarp/util/thread/logic.cpp:74
#1  0x00005555557ab6e0 in llarp::ILinkLayer::udp_tick (udp=0x7ffff0030998) at /home/stephen/dev/loki-network/llarp/link/server.cpp:469
#2  0x00005555558b89c3 in libuv::udp_glue::Tick (this=0x7ffff0031000) at /home/stephen/dev/loki-network/llarp/ev/ev_libuv.cpp:443
#3  0x00005555558b8971 in libuv::udp_glue::OnTick (t=0x7ffff00310e0) at /home/stephen/dev/loki-network/llarp/ev/ev_libuv.cpp:436
#4  0x00007ffff7f98a31 in uv.run_check () from /lib/x86_64-linux-gnu/libuv.so.1
#5  0x00007ffff7f9350d in uv_run () from /lib/x86_64-linux-gnu/libuv.so.1
#6  0x00005555558b63a2 in libuv::Loop::tick (this=0x7ffff001bad0, ms=100) at /home/stephen/dev/loki-network/llarp/ev/ev_libuv.cpp:767
#7  0x00005555558aa189 in llarp_ev_loop_run_single_process (ev=std::shared_ptr<llarp_ev_loop> (use count 5, weak count 0) = {...},
    logic=std::shared_ptr<llarp::Logic> (use count 7, weak count 0) = {...}) at /home/stephen/dev/loki-network/llarp/ev/ev.cpp:43
#8  0x00005555555d720c in llarp::Context::Run (this=0x7ffff00022d0, backgroundMode=true) at /home/stephen/dev/loki-network/llarp/context.cpp:247
#9  0x00005555555d7d4d in llarp_main_run (ptr=0x7ffff0001b50, backgroundMode=true) at /home/stephen/dev/loki-network/llarp/context.cpp:434
#10 0x00005555555850c3 in run_main_context (conffname="/home/stephen/.lokinet/lokinet.ini", multiThreaded=true, backgroundMode=true)
    at /home/stephen/dev/loki-network/daemon/main.cpp:105
#11 0x00005555555a8e99 in std::__invoke_impl<void, void (*&)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool&, bool&> (__f=@0x555555ca2088: 0x555555584f14 <run_main_context(std::__cxx11::string, bool, bool)>,
    __args#0="/home/stephen/.lokinet/lokinet.ini", __args#1=@0x555555ca2091: true, __args#2=@0x555555ca2090: true) at /usr/include/c++/8/bits/invoke.h:60
#12 0x00005555555a494a in std::__invoke<void (*&)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool&, bool&> (__fn=@0x555555ca2088: 0x555555584f14 <run_main_context(std::__cxx11::string, bool, bool)>,
    __args#0="/home/stephen/.lokinet/lokinet.ini", __args#1=@0x555555ca2091: true, __args#2=@0x555555ca2090: true) at /usr/include/c++/8/bits/invoke.h:95
#13 0x00005555555a0fc5 in std::_Bind<void (*(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool)>::__call<void, , 0ul, 1ul, 2ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (this=0x555555ca2088, __args=...)
    at /usr/include/c++/8/functional:400
#14 0x000055555559c971 in std::_Bind<void (*(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool)>::operator()<, void>() (this=0x555555ca2088) at /usr/include/c++/8/functional:484
#15 0x000055555559780b in std::__invoke_impl<void, std::_Bind<void (*(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool)>>(std::__invoke_other, std::_Bind<void (*(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool)>&&) (__f=...) at /usr/include/c++/8/bits/invoke.h:60
#16 0x000055555559336b in std::__invoke<std::_Bind<void (*(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool)>>(std::_Bind<void (*(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool)>&&) (__fn=...) at /usr/include/c++/8/bits/invoke.h:95
#17 0x00005555555d4ace in std::thread::_Invoker<std::tuple<std::_Bind<void (*(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool)> > >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x555555ca2088) at /usr/include/c++/8/thread:244
#18 0x00005555555d47c9 in std::thread::_Invoker<std::tuple<std::_Bind<void (*(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool)> > >::operator()() (this=0x555555ca2088) at /usr/include/c++/8/thread:253
#19 0x00005555555d3f80 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::_Bind<void (*(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool))(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool)> > > >::_M_run() (this=0x555555ca2080) at /usr/include/c++/8/thread:196
#20 0x00007ffff7e72630 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#21 0x00007ffff7c22182 in start_thread (arg=<optimized out>) at pthread_create.c:486
#22 0x00007ffff7b4bb1f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by neuroscr** [comment]
notlesh confirmed this is fixed in lokinet mtg
